### ISSUE TITLE
conversion job error

### ISSUE THREAD

**Issue by ghost** [vudung45/HLS-GoogleDrive#12]
Clicking Start to start the conversion job is throwing the error:

```
Error: Couldn't retry job: The job has been already retried or has not failed
    at C:\HLS-GoogleDrive\node_modules\bull\lib\job.js:356:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

i spent lots of time looking at this code and i don't understand this part in jobs-manager:

https://github.com/vudung45/HLS-GoogleDrive/blob/80cb85c9371aa796c4874906df6e6ea256a4d597/app/workers/jobs_manager.js#L85

also the convert_hls_worker.js is not being used , please give us some hints at least!

**Comment by vudung45** [comment]
convert_hls_worker.js should be ran seperately.
The process will receive job requests from redis queue, and initiate conversion job there.

Sorry for the lack of documentation. I will be writing some docs once I have time!

**Comment by ghost** [comment]
**Update:**

added the \app\credentials\service_accounts\*.json into workers folder and it works now finally!

--------------------------

now it makes sense! is it just normal `./node convert_hls_worker.js` ?

i did that and got the error : 

```
start
[Error: ENOENT: no such file or directory, scandir 'C:\HLS-GoogleDrive\dist\workers\app\credentials\service_accounts'] {
```

do i need to make the \app\credentials\service_accounts and put the json files ? or modify the `import GoogleCredentialsConfig from "../configs/googlecredentials.js";`

**Comment by lucasferrari3** [comment]
> Clicking Start to start the conversion job is throwing the error:
> 
> ```
> Error: Couldn't retry job: The job has been already retried or has not failed
>     at C:\HLS-GoogleDrive\node_modules\bull\lib\job.js:356:19
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ```
> 
> i spent lots of time looking at this code and i don't understand this part in jobs-manager:
> 
> https://github.com/vudung45/HLS-GoogleDrive/blob/80cb85c9371aa796c4874906df6e6ea256a4d597/app/workers/jobs_manager.js#L85
> 
> also the convert_hls_worker.js is not being used , please give us some hints at least!

I have the same problem here, any tips for me to give?

**Comment by ghost** [comment]
@lucasferrari3 copy the service accounts json files into `\HLS-GoogleDrive\dist\workers\app\credentials\service_accounts`

then cd into \HLS-GoogleDrive\dist\workers\
finally `node convert_hls_worker.js`


or you can do that without coping service accounts, just edit the file : googlecredentials.js

replace : "service_accounts": "./app/credentials/service_accounts"
with : "service_accounts": "../credentials/service_accounts"

**Comment by lucasferrari3** [comment]
> @lucasferrari3 copy the service accounts json files into `\HLS-GoogleDrive\dist\workers\app\credentials\service_accounts`
> 
> then cd into \HLS-GoogleDrive\dist\workers
> finally `node convert_hls_worker.js`
> 
> or you can do that without coping service accounts, just edit the file : googlecredentials.js
> 
> replace : "service_accounts": "./app/credentials/service_accounts"
> with : "service_accounts": "../credentials/service_accounts"

Thank you, I will test.

**Comment by lucasferrari3** [comment]
> @lucasferrari3 copy the service accounts json files into `\HLS-GoogleDrive\dist\workers\app\credentials\service_accounts`
> 
> then cd into \HLS-GoogleDrive\dist\workers
> finally `node convert_hls_worker.js`
> 
> or you can do that without coping service accounts, just edit the file : googlecredentials.js
> 
> replace : "service_accounts": "./app/credentials/service_accounts"
> with : "service_accounts": "../credentials/service_accounts"

I managed to make it work here, however WATCH doesn't work the page is blank

**Comment by ghost** [comment]
check my pull request to make watch page work.

**Comment by ateproni** [comment]
Hi...how to delete a file that has been converted and job ?  I want to delete some

**Comment by lucasferrari3** [comment]
> Hi...how to delete a file that has been converted and job ? I want to delete some

If it's the files on the drive, I can't tell because the names are all scrambled, in the script I usually delete it from the database.

**Comment by ateproni** [comment]
@lucasferrari3 yes to delete in database is very easy ,but that is not what I meant, thanks. 
Why job convertions always error result message: "The user's Drive storage quota"? What's wrong with my service account, how to fix?

**Comment by ateproni** [comment]
hello friends, I have a problem in the conversion section.  Only 1-2 files convert hls successfully, but then convert hls always fails.  How to fix it?
