### ISSUE TITLE
Transcoding file not working

### ISSUE THREAD

**Issue by paramov** [vudung45/HLS-GoogleDrive#7]
**Environment details**

- OS: Windows 10
- Node.js version: 12.3.1
- npm version: 6.14.4

**Error :**  file not downloading on server.

```
Server started on port 5001
{
  config: {
    url: 'https://www.googleapis.com/drive/v3/files/1wgj7_eXNQEVhk25QwZZ7ZzKPPjZEJr_V',
    method: 'GET',
    paramsSerializer: [Function],
    headers: {
      'x-goog-api-client': 'gdcl/3.2.2 gl-node/12.3.1 auth/5.10.1',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/3.2.2 (gzip)',
      Authorization: 'Bearer ' +
        'TOKEN',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    validateStatus: [Function],
    retry: true,
    responseType: 'json'
  },
  data: {
    kind: 'drive#file',
    id: '1wgj7_eXNQEVhk25QwZZ7ZzKPPjZEJr_V',
    name: 'DRAFT2.mp4',
    mimeType: 'video/mp4'
  },
  headers: {
    'alt-svc': 'quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ' +
      'ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ' +
      'ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ' +
      'ma=2592000,h3-T050=":443"; ma=2592000',
    'cache-control': 'private, max-age=0, must-revalidate, no-transform',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "frame-ancestors 'self'",
    'content-type': 'application/json; charset=UTF-8',
    date: 'Sun, 26 Apr 2020 21:00:40 GMT',
    expires: 'Sun, 26 Apr 2020 21:00:40 GMT',
    server: 'GSE',
    'transfer-encoding': 'chunked',
    vary: 'Origin, X-Origin',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'x-xss-protection': '1; mode=block'
  },
  status: 200,
  statusText: 'OK',
  request: {
    responseURL: 'https://www.googleapis.com/drive/v3/files/1wgj7_eXNQEVhk25QwZZ7ZzKPPjZEJr_V'
  }
}
{ fileId: '5ea5f6797791c025cc2fffeb', resolution: '1080p' }
Error: Couldn't retry job: The job has been already retried or has not failed
    at E:\HLS-GoogleDrive\node_modules\bull\lib\job.js:344:19
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by ghost** [comment]
@paramov same issue here, did you know whats the problem ?
